"""
Application logging configuration in ReachX.

Rather than using module-level loggers, opted to go with a single application-wide logger initially configured at
"INFO" level with two handlers:
   1. A rotating file handler that saves log messages at "INFO" level and higher to a dedicated application log file.
   2. An in-memory handler at "DEBUG" level which buffers log messages in a FIFO queue for access within ReachX itself.

During development and testing of ReachX, the application will have a "log view" that displays messages from the
second handler.

Usage:
 - Call `get_application_logger()` as early as possible to create and configure the singleton application-wide logger.
 - All future calls to the method simply retrieve the already-configured logger, so wherever you need to log a message,
   simply do, eg: get_application_logger().info(...). Alternatively, put _log = get_application_logger() near the top
   of a module, and use _log throughout the rest of the module code.
 - Pop the oldest message from the in-memory handler's FIFO queue by calling 'get_next_log_message()'.
 - NOTE that the application logger's two handlers will always log messages at their programmed level, even if the
   level of the logger itself is higher.


DEVNOTES:
 - Logger configuration is done programmatically rather than via configuration file.
"""
import logging
from collections import deque
from logging.handlers import RotatingFileHandler
from pathlib import Path
from typing import Deque, Optional

from reachx.common import RX

_RX = RX()
""" Application-wide constants. """

_LOGGER: str = 'ReachX'
""" Name of the application-wide logger we use. """
_LOG_DIR: str = 'logs'
""" Log files generated by the ReachX logger are placed in this subfolder under the user's ReachX home directory. """
_LOG_NAME: str = 'reachx.log'
""" The log file name. Backup will have '.0', etc appended to this. """
_NULL_LOGGER: str = 'ReachX_suppress_all'
""" Name of an application-wide logger that suppresses all log messages. """


class _LogViewHandler(logging.Handler):
    """
    A logging handler that pushes log messages into an internal fixed-size FIFO queue and provides methods to unload
    messages from that queue. We use this handler to provide an avenue by which the application log can be displayed
    in the application itself.
    """
    def __init__(self):
        super().__init__()
        self._message_q: Deque[str] = deque(maxlen=500)

    def emit(self, record):
        """
        Formats log record and pushes the resulting log message onto the internal FIFO queue. If the queue has
        reached capacity, the oldest message is dropped.
        """
        self._message_q.append(self.format(record))

    def get_next_log_message(self) -> Optional[str]:
        try:
            return self._message_q.popleft()
        except IndexError:
            return None


def get_application_logger() -> logging.Logger:
    """
    Get the singleton logger used to emit all logs from ReachX application code. On the first call, the root logger
    and the ReachX logger are configured. The root logger is configured only to emit logs at "WARNING" level and above
    -- so that we don't get too much crap on the console from third-party libraries. The application-wide logger is
    initially set to 'INFO' level and its handlers do not dump to the console at all. See module header for further
    details.

    :return: The logger to use in all ReachX application code.
    :raises RuntimeError: If unable to configure the application-wide logger on first invocation. This is considered a
       fatal error.
    """
    if not (_LOGGER in logging.root.manager.loggerDict):
        try:
            # configure root logger first
            root_handler = logging.StreamHandler()  # dumps to stderr by default
            root_handler.setLevel(logging.WARNING)
            logging.basicConfig(
                level=logging.WARNING,
                format='%(levelname)s: %(name)s: %(message)s',
                handlers=[root_handler]
            )

            # now set up app-wide logger at INFO level
            logger = logging.getLogger(_LOGGER)
            logger.setLevel(logging.INFO)

            # formatter used for all log messages
            formatter = logging.Formatter('%(asctime)s | %(levelname)s: [%(module)s] %(message)s',
                                          datefmt="%d %b %H:%M:%S")

            # rotating file handler logs INFO and above to a dedicated logs folder in user's home directory
            log_dir = Path(_RX.HOME, _LOG_DIR)
            log_dir.mkdir(parents=True, exist_ok=True)  # ensure the dedicated logs folder is there
            handler = RotatingFileHandler(Path(log_dir, _LOG_NAME), maxBytes=200*1024, backupCount=5)
            handler.setLevel(logging.INFO)
            handler.setFormatter(formatter)
            logger.addHandler(handler)

            handler = _LogViewHandler()
            handler.setLevel(logging.DEBUG)
            handler.setFormatter(formatter)
            logger.addHandler(handler)

            # This is the first message seen in log when ReachX is launched
            logger.info(f"{_RX.APP_NAME} {_RX.APP_VERSION} - Application logger started")
        except Exception as e:
            raise RuntimeError(f"Failed to create application-wide logger for ReachX: {str(e)}")

    return logging.getLogger(_LOGGER)


def get_next_log_message() -> Optional[str]:
    """
    Retrieve the oldest message from the application logger's internal queue.
    
    **NOTE**: This is the mechanism by which the application log can be displayed in the application itself. Once
    retrieved, the message is removed from the internal queue -- so this is intended only for use by a single GUI
    element dedicated to displaying the log.

    :return: The oldest log message still in the app logger's internal queue, or None if the queue is empty.
    """
    handlers = get_application_logger().handlers
    handler: Optional[_LogViewHandler] = next((h for h in handlers if isinstance(h, _LogViewHandler)), None)
    return None if handler is None else handler.get_next_log_message()


def get_null_logger() -> logging.Logger:
    """
    Get an application-wide logger that can be used to suppress all log messages. In ReachX, we use this to
    suppress log messages from code running on a background task that is reporting log messages in a different manner.

    :return: The "suppress all" logger object
    """
    if not (_NULL_LOGGER in logging.root.manager.loggerDict):
        null_logger = logging.getLogger(_NULL_LOGGER)
        null_logger.propagate = False  # Prevent messages from propagating to parent loggers
        null_logger.addHandler(logging.NullHandler())
    return logging.getLogger(_NULL_LOGGER)
